_target_: didactic.tasks.constraints.NeighborhoodConsistencyConstraint
cdist:
  _target_: vital.metrics.train.metric.RBFKernel
# pretrain-8d-0 v2.0.0
#  length_scale: [0.4149, 0.3322, 0.3865, 0.0270, 0.2760, 0.0423, 0.0066, 0.3673] # Estimate from Silverman's rule
#  length_scale: 0.1262 # Estimate from cross-validation
#  length_scale: 0.6455 # Estimate from Scott's rule (copy of scipy impl.)
#  length_scale: 0.5981 # Estimate from Silverman's rule (copy of scipy impl.)
#  length_scale: 0.3454 # Mean distance to 5 nearest neighbors
#  length_scale: 0.4059 # Mean distance to 8 nearest neighbors
# pretrain-8d-0 v3.0.0
  length_scale: 0.4231 # Mean distance to 5 nearest neighbors
# pretrain-mask-8d-0 v1.0.0
#  length_scale: 0.6095 # Mean distance to 5 nearest neighbors

affinity_matrices_loss:
  _target_: ???

affinity_eps: 1e-3
