_target_: didactic.models.irene.Encoder
config:
  hidden_size: 768
  transformer:
    mlp_dim: 3072
    num_heads: 12
    num_layers: 12
    attention_dropout_rate: 0.1 # 0.0 - 0.2
    dropout_rate: 0.3 # 0.1 - 0.3
  classifier: token
  representation_size: null
