defaults:
  - xtab

n_self_blocks: 6
attention_n_heads: 2
attention_normalization:
  normalized_shape: ${op.mul:1.5,${task.model.encoder.d_token},int}
ffn_d_hidden: ${op.mul:1.5,${task.model.encoder.d_token},int}
ffn_normalization:
  normalized_shape: ${op.mul:1.5,${task.model.encoder.d_token},int}
